// Auto-generated by Claude Code workflow block 4 (FAQs par page)
// Genere le 2026-06-15. Source: workflow parallele de 10 agents Claude.

export type FaqItem = { question: string; answer: string };
export type FaqPageData = {
  pageKey: string;
  title: string;
  description: string;
  items: FaqItem[];
};

export const faqsByPage: Record<string, FaqPageData> = {
  "services": {
    pageKey: "services",
    title: "Comprendre les services SKS Talents avant de nous solliciter",
    description: "Reponses concretes pour un.e CEO, COO ou DRH de scale-up biotech, diagnostic, medtech, veterinaire ou petfood.",
    items: [
      {
        question: "Quels services SKS Talents couvre vraiment pour une scale-up Life Sciences ou Animal Health ?",
        answer: "SKS Talents couvre trois services distincts : executive search sur fonctions cadres et dirigeantes, RPO pour absorber un pic de recrutement, et structuration RH (process, grilles, onboarding). L'automatisation RH avec IA est vendue separement via les landings dediees. Tous nos mandats restent ancres Life Sciences et Animal Health, jamais generalistes."
      },
      {
        question: "Sur quelles fonctions intervenez-vous en executive search ?",
        answer: "Nous intervenons sur les fonctions cadres et dirigeantes : un.e CEO, COO, CMO, CSO, VP Clinical, Head of Manufacturing, DRH, Director Regulatory ou Country Manager. Le perimetre couvre biotech, diagnostic, medtech, vaccins veterinaires et petfood premium. Chaque mandat est conduit par un.e consultant.e sectoriel.le, jamais par un generaliste recrutement."
      },
      {
        question: "Quelle est la difference entre executive search et RPO chez vous ?",
        answer: "L'executive search cible une fonction strategique unique, avec approche directe confidentielle et shortlist resserree. Le RPO absorbe un volume - typiquement 5 a 15 postes simultanes sur une levee de fonds ou une phase clinique - avec un.e recruteur.se integre.e a votre equipe. Les deux peuvent se cumuler sur une meme scale-up en croissance rapide."
      },
      {
        question: "Pourquoi separer la structuration RH du recrutement classique ?",
        answer: "La structuration RH traite les fondations : grilles de remuneration, process d'evaluation, onboarding, politique equity. Sans ces fondations, un.e dirigeant.e recrute, puis perd ses talents en 18 mois. Le turnover moyen biotech atteint des niveaux preoccupants en phase scale-up (Source : France Biotech x EY 2025). Nous installons ces fondations en amont ou en parallele du recrutement."
      },
    ]
  },
  "life-sciences": {
    pageKey: "life-sciences",
    title: "Recruter ses cadres Life Sciences : 4 questions cles",
    description: "FAQ destinee aux dirigeant.e.s biotech, medtech et diagnostic qui evaluent un partenaire exec search Life Sciences pour structurer leur equipe cadre.",
    items: [
      {
        question: "Sur quelles fonctions cadres Life Sciences intervenez-vous concretement ?",
        answer: "Nous couvrons les fonctions strategiques d'une biotech, medtech ou societe de diagnostic : CEO, CSO, CTO, VP R&D, Head of Regulatory, COO et CMO. Les missions concernent des structures de la Seed a la scale-up, en France et en Europe, avec une priorite sur les profils ayant deja scale un produit reglemente."
      },
      {
        question: "Avez-vous l'experience des biotech au stade Seed ou Serie A, pas seulement des scale-up ?",
        answer: "Oui, environ une mission sur deux concerne une Seed ou Serie A. A ce stade, le besoin n'est pas un.e cadre senior generaliste mais un.e operateur.rice qui sait avancer sans equipe, gerer la levee suivante et poser les premieres briques reglementaires. Nous calibrons la shortlist sur cette realite."
      },
      {
        question: "Combien de temps prend un recrutement de CSO ou VP R&D en Life Sciences ?",
        answer: "Le time-to-hire moyen observe sur le marche se situe entre 4 et 7 mois pour une fonction scientifique cadre (Source : France Biotech x EY 2025). Sur nos missions, le.la candidat.e signe en general autour de 12 a 14 semaines, grace a un mapping marche prepare en amont du brief."
      },
      {
        question: "Travaillez-vous aussi sur la deeptech sante et le diagnostic IVD/NGS, ou seulement la biotech therapeutique ?",
        answer: "Les deux. Nous recrutons pour des societes de diagnostic IVD, plateformes NGS, medtech implantable et deeptech sante (IA medicale, robotique chirurgicale). Le point commun reste un produit reglemente, un cycle de developpement long et une exigence forte sur la double competence scientifique et business du.de la candidat.e cible."
      },
    ]
  },
  "animal-health": {
    pageKey: "animal-health",
    title: "Recruter en Animal Health : ce qu'il faut savoir",
    description: "Reperes pour les dirigeant.e.s qui structurent leurs equipes cliniques veterinaires, petfood, diagnostic et pharma veterinaire.",
    items: [
      {
        question: "Pourquoi recruter un.e Directeur.rice de groupement veterinaire est-il aussi tendu en 2025 ?",
        answer: "Le vivier reste etroit car le marche s'est consolide vite et les profils combinant gestion multisites, P&L et leadership clinique sont rares. Les groupements cherchent des dirigeant.e.s capables de tenir la promesse medicale tout en pilotant la croissance. SKS Talents cartographie ces profils par region et par typologie d'actionnaire."
      },
      {
        question: "Quelle difference entre un.e COO clinique et un.e directeur.rice operationnel.le classique ?",
        answer: "Le ou la COO clinique pilote a la fois la performance economique et la qualite des soins, en lien direct avec les veterinaires associes. Il ou elle gere la standardisation des protocoles, le recrutement medical, et la coordination multisites. Le profil exige une double culture sante animale et operations, rare sur le marche francais."
      },
      {
        question: "Comment structurer une equipe R&D petfood en phase de scale-up ?",
        answer: "Commencez par un.e Head of R&D capable de prioriser nutrition, formulation et claims reglementaires. Ajoutez un.e responsable affaires reglementaires des le passage europeen, puis un.e scientifique senior par axe (felin, canin, fonctionnel). SKS Talents accompagne ces sequencements pour eviter les recrutements premature.s ou redondants."
      },
      {
        question: "Le ou la MSL veterinaire est-il un profil cle pour un labo pharma animale ?",
        answer: "Oui, le ou la MSL veterinaire fait le lien entre la R&D, les KOL veterinaires et les equipes commerciales. Il ou elle porte l'evidence scientifique sur le terrain, ce qui devient critique sur les lancements vaccin, oncologie veterinaire ou parasitologie. Le vivier francophone reste limite, surtout sur les especes de production."
      },
    ]
  },
  "diagnostic": {
    pageKey: "diagnostic",
    title: "Diagnostic IVD, NGS et point of care : les questions cles",
    description: "Pour les dirigeant.e.s du secteur diagnostic qui structurent leur equipe face a l'IVDR, au NGS et a l'integration laboratoire.",
    items: [
      {
        question: "L'IVDR change quoi concretement pour mon equipe regulatory affairs diagnostic ?",
        answer: "L'IVDR reclasse environ 80% des dispositifs IVD en classes B, C ou D, contre 7% sous l'ancienne directive (Source : France Biotech x EY 2025). Concretement, il faut un.e Person Responsible for Regulatory Compliance dedie.e, des dossiers techniques renforces et un suivi post-market actif. Le recrutement RA diagnostic devient critique des le seed."
      },
      {
        question: "Quels profils recruter en priorite pour lancer une plateforme NGS clinique ?",
        answer: "Trois profils sont structurants. Un.e bioinformaticien.ne senior pour le pipeline variant calling, un.e responsable assurance qualite ISO 15189, et un.e medical affairs avec experience anapath moleculaire. L'integration LIMS et la validation analytique des panels conditionnent le time-to-market. SKS Talents recrute ces trois fonctions en parallele."
      },
      {
        question: "Pourquoi l'integration HL7 et LIMS bloque autant les deploiements diagnostic ?",
        answer: "L'integration HL7 FHIR et LIMS est rarement portee par un.e seul.e profil. Elle exige un.e architecte logiciel cote IVD, un.e specialiste interoperabilite hopital, et un.e clinical application specialist. Sans ce trio, le go-live derape de 6 a 12 mois. C'est un point de douleur recurrent observe en mission."
      },
      {
        question: "La cybersecurite OT en laboratoire, c'est un sujet recrutement ou DSI ?",
        answer: "Les deux. L'analyseur IVD connecte est un endpoint OT regule, pas un PC de bureau. Il faut un.e responsable cybersecurite avec double culture IEC 81001-5-1 et IT hospitaliere. Ce profil hybride est rare sur le marche francais. SKS Talents l'identifie via sourcing croise medtech, pharma industrielle et editeurs LIMS."
      },
    ]
  },
  "orientation": {
    pageKey: "orientation",
    title: "Orientation Life Sciences : ce qu'il faut savoir",
    description: "Reperes pour orienter un.e jeune vers les metiers biotech, HealthTech et Animal Health, ou batir une politique alternance solide.",
    items: [
      {
        question: "Quels parcours mènent réellement aux métiers biotech aujourd'hui ?",
        answer: "Trois voies dominent : écoles d'ingénieurs (AgroParisTech, Centrale, INSA), universités (master biotech, bio-ingénierie, pharma) et écoles vétérinaires pour l'Animal Health. Les profils data et bio-informatique passent souvent par un double cursus sciences plus informatique. Le BTS biotechnologies et les licences pro alimentent les fonctions techniciens et production des sites industriels."
      },
      {
        question: "Quelles fonctions recrutent le plus côté biotech et HealthTech ?",
        answer: "Les fonctions R et D restent prioritaires (biologie, chimie, formulation), suivies par les affaires réglementaires, le clinical operations et la production GMP. Côté HealthTech, la demande porte sur data science santé, machine learning et product management. L'industrie biotech française compte environ 800 entreprises actives (Source : France Biotech x EY 2025)."
      },
      {
        question: "Une reconversion vers les Life Sciences est-elle réaliste après 35 ans ?",
        answer: "Oui, à condition de cibler les fonctions transverses : qualité, affaires réglementaires, business development, RH spécialisée, finance et project management. Les profils issus du conseil, de la pharma ou du digital sont régulièrement intégrés. Un.e candidat.e crédible documente un parcours sectoriel via certifications courtes, missions freelance ou alternance cadre."
      },
      {
        question: "Pourquoi un cabinet exec search publie-t-il une page orientation ?",
        answer: "Parce que la pénurie de talents Life Sciences se prépare en amont du marché cadre. Aider lycéen.ne.s, étudiant.e.s et personnes en reconversion à comprendre le secteur élargit le vivier dans lequel nos clients recruteront dans cinq à dix ans. C'est un service public utile, distinct de notre activité executive search facturée aux entreprises."
      },
    ]
  },
  "investment-funds": {
    pageKey: "investment-funds",
    title: "Cartographie fonds sante : questions des dirigeants",
    description: "Reperes pratiques pour CEO et CFO Life Sciences ou Animal Health qui preparent une levee et veulent cadrer leur shortlist d'investisseurs.",
    items: [
      {
        question: "A quoi sert cette cartographie des fonds sante avant une levee ?",
        answer: "Elle sert a cadrer une shortlist d'investisseurs avant les premiers contacts. Vous identifiez les fonds actifs en biotech, medtech, healthtech ou animal health, leurs tickets typiques et leurs stades d'intervention. Cela evite de disperser l'energie du CEO sur des fonds hors-these et de bruler des cartouches au mauvais moment du process."
      },
      {
        question: "Comment choisir entre un fonds biotech specialise et un fonds healthtech generaliste ?",
        answer: "Le choix depend du risque scientifique porte par l'actif. Un fonds biotech specialise comprend les jalons cliniques et accepte la duree. Un fonds healthtech generaliste va plus vite sur des modeles SaaS ou services, mais reste prudent sur le regulatoire. Croisez stade, ticket et expertise sectorielle avant de prioriser votre shortlist."
      },
      {
        question: "Quels signaux montrent qu'un fonds est reellement actif en sante en 2026 ?",
        answer: "Trois signaux concrets : deals annonces sur les 12 derniers mois, presence d'un.e partner dedie.e sante au comite, et participations existantes au stade vise. Un fonds qui n'a pas signe depuis 18 mois sur votre verticale est souvent en pause LP. Le marche biotech europeen reste tendu (Source : France Biotech x EY 2025)."
      },
      {
        question: "Pourquoi structurer l'equipe RH avant la levee plutot qu'apres le closing ?",
        answer: "Parce que les fonds regardent la profondeur du board et du comex avant de signer. Un.e CFO solide, un.e CMO credible et un plan de hiring 18 mois rassurent sur l'execution. SKS intervient en amont sur le scope exec search et la structuration RH, distinctement de l'offre IA reservee aux landings dediees."
      },
    ]
  },
  "scorecard-dirigeant": {
    pageKey: "scorecard-dirigeant",
    title: "Scorecard dirigeant : reponses pour structurer la decision",
    description: "Reponses aux questions des CEO, boards et hiring committees qui veulent objectiver un recrutement C-level en Life Sciences.",
    items: [
      {
        question: "A quoi sert concretement une scorecard dirigeant dans un recrutement C-level ?",
        answer: "Une scorecard transforme une decision intuitive en decision structuree. Elle aligne le CEO, le board et le hiring committee sur 5 a 8 criteres mesurables (impact attendu, competences cles, fit culturel, signaux de risque). Resultat : moins de biais individuel, moins de mis-hires, et un debrief post-entretien comparable entre candidat.e.s."
      },
      {
        question: "Quand un.e CEO de biotech ou animal health doit-il/elle utiliser une scorecard plutot qu'un debrief libre ?",
        answer: "Des qu'il y a plus de deux decideurs ou un poste structurant (CSO, COO, CFO, VP Clinical). Le debrief libre favorise la voix dominante du board. La scorecard force chaque membre du comite a noter avant la discussion, ce qui revele les desaccords reels et evite les recrutements de consensus mou."
      },
      {
        question: "Comment construire les criteres de la scorecard sans tomber dans la check-list generique ?",
        answer: "Partez des 3 livrables attendus du poste sur 18 mois (closing serie B, depot IND, scale commerciale). Chaque critere doit etre rattache a un livrable, pas a une competence abstraite. Ajoutez 2 criteres de fit (rapport au board, gestion d'incertitude). Evitez le critere leadership seul, trop vague pour etre note."
      },
      {
        question: "Est-ce que SKS Talents fournit la scorecard ou accompagne le hiring committee ?",
        answer: "Les deux. SKS Talents intervient comme cabinet d'executive search Life Sciences et Animal Health, et structure le hiring committee en amont : definition des criteres, calibrage des notes, animation du debrief. La scorecard est un livrable de la mission de recrutement, pas un outil isole vendu separement."
      },
    ]
  },
  "calcul-salaire-brut-net": {
    pageKey: "calcul-salaire-brut-net",
    title: "Salaire brut net cadres Life Sciences : ce qu'il faut savoir",
    description: "Reponses concretes pour dirigeant.e.s qui calibrent un package cadre en biotech, medtech ou animal health.",
    items: [
      {
        question: "Quel ecart brut-net dois-je anticiper pour un.e cadre en biotech francaise ?",
        answer: "Comptez environ 22 a 25% de charges salariales sur un statut cadre standard, soit un net avant impot proche de 77% du brut. L'ecart varie selon la mutuelle, la prevoyance et le niveau de remuneration. Notre calculateur integre les specificites du statut cadre Life Sciences pour une projection fiable lors d'une offre."
      },
      {
        question: "Comment integrer les BSPCE dans le calcul de la remuneration totale ?",
        answer: "Les BSPCE ne s'ajoutent pas au salaire brut. Ils constituent une remuneration differee, taxee a la cession des titres, pas au versement. Le calculateur isole le cash (brut/net) du package equity. Pour un.e VP ou C-level scaleup, cette distinction evite de survendre une offre lors de la negociation."
      },
      {
        question: "Le statut cadre change-t-il vraiment le net percu chaque mois ?",
        answer: "Oui, le statut cadre majore la cotisation retraite complementaire AGIRC-ARRCO et la prevoyance obligatoire (1,50% sur la tranche 1). Le net mensuel est donc legerement inferieur a celui d'un.e non-cadre a brut equivalent, mais la couverture prevoyance et la retraite future sont superieures."
      },
      {
        question: "Comment traiter les primes variables et bonus dans une offre cadre ?",
        answer: "Le variable cible s'exprime en brut annuel et subit les memes charges que le fixe. Affichez toujours fixe brut + variable cible + equity separement. Selon AON x France Biotech 2025, le variable represente 15 a 25% du fixe pour un.e Director et 25 a 40% pour un.e C-level en biotech (Source : AON x France Biotech 2025)."
      },
    ]
  },
  "about": {
    pageKey: "about",
    title: "Mieux comprendre SKS Talents avant un premier echange",
    description: "Reperes concrets pour un.e dirigeant.e Life Sciences ou Animal Health qui evalue notre cabinet avant de confier une mission cadre.",
    items: [
      {
        question: "Pourquoi choisir un cabinet specialise Life Sciences plutot qu'un generaliste ?",
        answer: "Parce que la lecture sectorielle change le resultat. Huit ans dedies a la Life Sciences et a l'Animal Health donnent une cartographie fine des profils CMC, affaires reglementaires, medical, BD ou industriel. Le/la dirigeant.e gagne du temps de qualification, evite les erreurs de casting et accede a un vivier deja approche en confidentiel."
      },
      {
        question: "Quelles preuves de serieux puis-je verifier avant de vous confier une mission ?",
        answer: "Trois reperes concrets. Plus de 100 placements realises, 18 missions actives en cours et 75% de retention a cinq ans sur les profils places. S'ajoutent la presence en Commission RH France Biotech et le partenariat avec l'Universite Paris-Saclay. Ces signaux permettent de juger la stabilite du cabinet sans se fier au discours commercial."
      },
      {
        question: "Quel est le lien entre vos missions de recrutement et votre offre IA ?",
        answer: "Ce sont deux services distincts. Le coeur du cabinet reste l'executive search Life Sciences et Animal Health. L'offre de structuration RH par IA s'adresse separement aux equipes qui veulent industrialiser leurs process internes. Un.e dirigeant.e peut faire appel uniquement au recrutement, sans engagement sur le volet IA."
      },
      {
        question: "Comment travaillez-vous avec une biotech ou une scaleup qui recrute son premier cadre cle ?",
        answer: "Par un cadrage prealable serre. Avant toute approche, le/la dirigeant.e clarifie avec nous le scope du poste, la trajectoire de financement et les criteres de reussite a douze mois. Ensuite, approche directe ciblee, short list courte, restitution structuree. L'objectif est de securiser une prise de poste qui tient dans la duree."
      },
    ]
  },
  "references": {
    pageKey: "references",
    title: "References clients : ce que vous pouvez verifier",
    description: "FAQ pour CEO et DRH Life Sciences ou Animal Health qui veulent valider la credibilite sectorielle de SKS Talents avant un brief.",
    items: [
      {
        question: "Sur quels segments SKS Talents a-t-il deja livre des placements ?",
        answer: "SKS Talents intervient sur cinq segments : biotech, diagnostic in vitro, medtech, sante animale et petfood. Les missions couvrent des postes de direction (CEO, COO, CMO, CSO) et des fonctions cles R&D, affaires reglementaires, acces marche. Chaque reference est consultable sur demande, avec accord prealable du/de la client.e."
      },
      {
        question: "Comment verifier la realite des references avant un brief ?",
        answer: "Demandez un echange de 20 minutes avec un.e client.e referent.e du meme segment. SKS Talents organise la mise en relation apres accord, sur les 18 missions livrees (7 Animal Health, 11 Life Sciences). Vous obtenez un retour direct sur la methode, le delai et la qualite du shortlist."
      },
      {
        question: "Quel est le taux de retention des cadres places par SKS Talents ?",
        answer: "Le taux de retention a cinq ans atteint 75 % sur les missions livrees depuis 2019. Ce chiffre couvre les placements executifs et middle management toutes scopes confondus. Il est verifiable mission par mission lors de l'echange de calibration, avec les noms des dirigeant.e.s encore en poste aujourd'hui."
      },
      {
        question: "Travaillez-vous avec des scaleups pre-revenus ou seulement des structures matures ?",
        answer: "SKS Talents couvre les deux profils. Cote scaleups, le cabinet accompagne des biotechs en Serie A ou B sur les premiers recrutements C-level. Cote structures matures, il gere des remplacements strategiques et creations de poste. Le segment biotech francais a leve 1,3 Md EUR en 2024 (Source : France Biotech x EY 2025)."
      },
    ]
  },
};
